-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgPwnDKa/bFIFwjWFg
wtW5ryprprL/DFWNzxnDCYFz3zCgCgYIKoZIzj0DAQehRANCAASsfKRM49JqTJ/A
x3HPsFzGT56+4oBMxYcv6RItKDCVKGdGHhBfEc0b1DGZdfM4FsYVLJjDVL5A9C1E
lG+mLja9
-----END PRIVATE KEY-----